"""
Django settings for whosbug project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'v$a_u8#y6@br%3%@ojcud-$r%8^gc^j=-lnkoiug6dui+h%lgf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'mainapp',
#    'rest_framework_swagger',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'whosbug.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':[os.path.join(BASE_DIR, 'templates')],  # 指定templates模板目录路径 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'whosbug.wsgi.application'

# REST_FRAMEWORK = {
#     'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema'
# }

# Database

# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
if os.environ.get("POSTGRES_DBNAME"):
    POSTGRES_DBNAME = os.environ.get("POSTGRES_DBNAME")
else:
    POSTGRES_DBNAME = 'whosbug'
if os.environ.get("POSTGRES_USER"):
    POSTGRES_USER = os.environ.get("POSTGRES_USER")
else:
    POSTGRES_USER = 'guest'
if os.environ.get("POSTGRES_PASSWORD"):
    POSTGRES_PASSWORD = os.environ.get("POSTGRES_PASSWORD")
else:
    POSTGRES_PASSWORD = 'guest'
if os.environ.get("POSTGRES_HOST"):
    POSTGRES_HOST = os.environ.get("POSTGRES_HOST")
else:
    POSTGRES_HOST = '39.101.192.144'
if os.environ.get("POSTGRES_PORT"):
    POSTGRES_PORT = os.environ.get("POSTGRES_PORT")
else:
    POSTGRES_PORT = 5432

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',  # 指定用什么数据库
        'NAME': POSTGRES_DBNAME,  # 指定数据库名
        'USER': POSTGRES_PASSWORD,  # 数据库账号
        'PASSWORD': POSTGRES_PASSWORD,  # 数据库密码
        'HOST': POSTGRES_HOST,  # 数据库IP 本机用localhost
        'PORT': POSTGRES_PORT,  # 端口
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
login_url='/login/'


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Session
SESSION_COOKIE_AGE = 43200             # Session的cookie失效日期（2周）（数字为秒数）（默认）
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # 是否关闭浏览器使得Session过期（默认）
SESSION_SAVE_EVERY_REQUEST = True       # 是否每次请求都保存Sessions

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
#try:
#    from .local_settings import *
#except ImportError:
#    pass
