# Generated by Django 2.2 on 2020-08-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200809_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='functionname',
            field=models.CharField(max_length=200),
        ),
    ]
